### ISSUE TITLE
TimeUnix (int64) in second should be a float64 to allow milliseconds after coma

### ISSUE THREAD

**Issue by rawouter** [gemnasium/logrus-graylog-hook#2]
Hello Gravis,

First of all, thanks a lot for this great logrus hook!

I'm using it in a distributed application written in various language. Because of that, I need to be able to trace the logs with millisecond precision otherwise graylog will not display them in order.

I forked this project, hoping I'd be able to do a merge request, but the gelf.Writer library you are using doesn't allow the gelf.Message to be a float64, and I also had to add a modified copy of it to my fork to have this working. Hence opening this bug instead of submitting a merge request.

Here is the project:
https://github.com/RaphYot/logrus-graylog-hook

I'm doing this conversion so that I can get the 3 millisecond numbers after the .  separation of the TimeUnix in second:

    		TimeUnix: float64(time.Now().UnixNano()/1000000) / 1000.,

Note that I also modified the README page to reflect the new repo, in the example it's still showing the legacy one.

Thanks!
Raph

**Comment by gravis** [comment]
Hi Ralph,
Sorry for the long delay.
Interesting change. Do you think you can rebase and create a pull request?
The github.com/SocialCodeInc/go-gelf/ repo hasn't be updated in a while but have at least some test.
We could also vendor it in a gelf directory in the logrus-graylog-hook (or you can propose a pull request on github.com/SocialCodeInc/go-gelf too).

Thanks
Philippe

**Comment by saward** [comment]
I'd be interested in seeing this included too.

**Comment by gravis** [comment]
merged in [v2.0.0](https://github.com/gemnasium/logrus-graylog-hook/tree/v2.0.0)
