### ISSUE TITLE
case-insensitive import collision Sirupsen

### ISSUE THREAD

**Issue by yuancheng-p** [gemnasium/logrus-graylog-hook#23]
Hi, when using the gralog-hook, the package could not compile with the following message: 

```
case-insensitive import collision: "vendor/github.com/Sirupsen/logrus" and "vendor/github.com/sirupsen/logrus"
```

The https://github.com/sirupsen/logrus has changed the from "Sirupsen" to "sirupsen".
More details here: 
* https://github.com/sirupsen/logrus/issues/451#issuecomment-264332021
* https://github.com/sirupsen/logrus/pull/384

Note that I've vendored the latest logrus and I had to modify the logrus-gralog-hook's import locally.
Maybe logrus-gralog-hook should update the import statements with lower case "sirupsen"?

**Comment by yuancheng-p** [comment]
@gravis thanks for fixing. When do you plan to update the dependency in gopkg.in/gemnasium/logrus-graylog-hook.v2 ?

**Comment by gravis** [comment]
Oops, I forgot the branches... right away :)

**Comment by gravis** [comment]
Done!

**Comment by bkleef** [comment]
@gravis thanks a lot for fixing this for @yuancheng-p but this change broke all our 100+ repos. I suggest to use a capital S as all examples use a capital S: https://github.com/sirupsen/logrus#example and only change it to lowercase when https://github.com/sirupsen/logrus/pull/526 is accepted.

**Comment by gravis** [comment]
@bkleef really for that, it wasn't intended of course.
Regarding sirupsen/logrus#526, if it's not merged today, I'll revert my change, and wait for the merge. Sounds good to you?

**Comment by gravis** [comment]
@bkleef you're right, the change WAS reverted, I went a little too fast here.
As I appear to be the only active maintainer of this repo, I will remove today's commits and tags completely, to avoid confusion (and let me find the time to solve this issue with my head focused...)

**Comment by gravis** [comment]
Reverted, sorry for this mess, I went way too fast into this issue.

**Comment by bkleef** [comment]
@gravis thanks a lot for your very fast action and reply! Sounds great, thanks a lot!

**Comment by yuancheng-p** [comment]
Hi @bkleef  and @gravis , I feel so sorry for bothering.
I agree to stick to the upper-case "S".

Actually I used glide for vendoring but since the repository url revert to lower-case now, it can not find resolve the package.

```
$ glide get github.com/Sirupsen/logrus
...
[ERROR]	Update failed for github.com/Sirupsen/logrus: The Remote does not match the VCS endpoint
[ERROR]	Failed to checkout packages: The Remote does not match the VCS endpoint
```

Here I got a work around solution to solve this : https://github.com/sirupsen/logrus/pull/384#issuecomment-264035988
