### ISSUE TITLE
Log level for hook

### ISSUE THREAD

**Issue by stgleb** [gemnasium/logrus-graylog-hook#25]
Why you've not added log level field for hook? I' suffering from the same problem in logstash hook.
I am developing high performance system and it degrade very much if it needs to allocate memory per each log entry, I want just to collect those messages that have severity INFO or higher.

**Comment by gravis** [comment]
You may want to use the `Level` field then: https://github.com/gemnasium/logrus-graylog-hook/blob/master/graylog_hook.go#L28
