### ISSUE TITLE
Low performance due to GC on gzip/zlib writers

### ISSUE THREAD

**Issue by jorygeerts** [gemnasium/logrus-graylog-hook#33]
The code in `graylog.Writer.WriteMessage()` constructs a new gzip/zlib writer for every message. This slows down the entire application (over 50% of my application time was spent in `runtime.gcDrain()`).

By only creating a gzip/zlib writer once, this overhead is removed, speeding everything up.

**Comment by jorygeerts** [comment]
@gravis From the looks of it, you seem in charge of this project. Could you take a look at my PR? Thanks!
(Sorry to ping you like this, but I have no idea if you're being notified about issues and PRs.)

**Comment by gravis** [comment]
Thanks for your contribution, and sorry for being late on this. I will review that by the end of the week.
