### ISSUE TITLE
Incompatible with go 1.11 package won't build when install with go get

### ISSUE THREAD

**Issue by choestelus** [gemnasium/logrus-graylog-hook#40]
in go version 1.11  I was failed to run `go get gopkg.in/gemnasium/logrus-graylog-hook.v2`

the error message was
```
# gopkg.in/gemnasium/logrus-graylog-hook.v2
go/src/gopkg.in/gemnasium/logrus-graylog-hook.v2/error.go:52:15: cannot convert stacktrace[0] (type "github.com/pkg/errors".Frame) to type uintptr
```

so I fixed this line from
```go
pc := uintptr(stacktrace[0])
```
into 
```go
pc := stacktrace[0].PC
```

and it seems to be working fine.

so I open this issue waiting it to be fixed soon. what do you think about this particular change?

**Comment by robsliwi** [comment]
I experience the same issue and the workaround is working for me.
I would opt-in for a PR with those line-change?

**Comment by TheSchemm** [comment]
Yep. I am now experiencing that problem as well.

**Comment by gravis** [comment]
Thanks for your contribution!
Actually, this is going to be fixed directly by https://github.com/gemnasium/logrus-graylog-hook/pull/39, which will be merged very soon.

**Comment by gravis** [comment]
Could you test with the new `v3` version of this plugin, and reopen this issue if you encounter any problem? Thank

**Comment by choestelus** [comment]
v3 seems to work fine now, thank you so much!
but my import path is `import graylog "github.com/gemnasium/logrus-graylog-hook"`
not `import graylog "github.com/gemnasium/logrus-graylog-hook/v3"`
