### ISSUE TITLE
3.0.1 tag is needed in order to get v3 using go modules

### ISSUE THREAD

**Issue by psampaz** [gemnasium/logrus-graylog-hook#45]
The only way to actual get the v3 is to use the following:

go get github.com/gemnasium/logrus-graylog-hook/v3@84ae10c40

Since the fix for module path was introduced after 3.0.0 in #42 the only way to make this work normally is a new bugfix version 3.0.1

**Comment by gravis** [comment]
I just released 3.0.1: https://github.com/gemnasium/logrus-graylog-hook/releases/tag/v3.0.1
Thanks for the heads up
