### ISSUE TITLE
Error value in log.Fields disappears or  errors tend to print as '{}'

### ISSUE THREAD

**Issue by agarwalyash02** [gemnasium/logrus-graylog-hook#61]
when adding an error in the field if we pass the error interface instead of passing err.Error() which is a string, cannot able to print the error message properly it only shows '{}' in the Graylog UI

**Comment by agarwalyash02** [comment]
Have fixed this issue in the PR: https://github.com/gemnasium/logrus-graylog-hook/pull/62

**Comment by gravis** [comment]
I have released v3.2.1 with this bug fix. Thanks!
