### ISSUE TITLE
gopkg.in's version

### ISSUE THREAD

**Issue by vanillahsu** [gemnasium/logrus-graylog-hook#7]
Hi:

any plan to update gopkg.in's version to 1.1.1?

I'd like to use async logger on my env,

thanks.

**Comment by gravis** [comment]
Hi,
Thanks for pointing this!
I had created tags without the leading 'v', so they were not recognized by gopkg.in
I have updated the tags, and http://gopkg.in/gemnasium/logrus-graylog-hook.v1 is accurate.
Cheers
